# Generated by Django 3.2.12 on 2022-09-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBookmark',
            fields=[
                ('bookmark_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_bookmark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbBroadcastingAlarm',
            fields=[
                ('broadcasting_alarm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_broadcasting_alarm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCast',
            fields=[
                ('cast_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('play_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_cast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbChat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbConditionGenre',
            fields=[
                ('genre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_condition_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbConditionProgram',
            fields=[
                ('condition_program_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_condition_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbConditionWithWhom',
            fields=[
                ('with_whom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('who', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_condition_with_whom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbGenderAgeViewer',
            fields=[
                ('gender_age_viewer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('female0', models.FloatField(blank=True, null=True)),
                ('female10', models.FloatField(blank=True, null=True)),
                ('female20', models.FloatField(blank=True, null=True)),
                ('female30', models.FloatField(blank=True, null=True)),
                ('female40', models.FloatField(blank=True, null=True)),
                ('female50', models.FloatField(blank=True, null=True)),
                ('female60', models.FloatField(blank=True, null=True)),
                ('genre_lclas', models.CharField(blank=True, max_length=255, null=True)),
                ('genre_mlsfc', models.CharField(blank=True, max_length=255, null=True)),
                ('genre_sclas', models.CharField(blank=True, max_length=255, null=True)),
                ('male0', models.FloatField(blank=True, null=True)),
                ('male10', models.FloatField(blank=True, null=True)),
                ('male20', models.FloatField(blank=True, null=True)),
                ('male30', models.FloatField(blank=True, null=True)),
                ('male40', models.FloatField(blank=True, null=True)),
                ('male50', models.FloatField(blank=True, null=True)),
                ('male60', models.FloatField(blank=True, null=True)),
                ('program_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_gender_age_viewer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbGenre',
            fields=[
                ('genre_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbGenreInfo',
            fields=[
                ('genre_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_genre_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbKDrama',
            fields=[
                ('k_drama_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brdcst_de', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_end_de', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_time', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_tme_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('chnnel_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('cst_cn', models.CharField(blank=True, max_length=1000, null=True)),
                ('female_4_9yo_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n10s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n20s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n30s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n40s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n50s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n60s_above_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_4_9yo_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n10s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n20s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n30s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n40s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n50s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n60s_above_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('program_begin_time', models.CharField(blank=True, max_length=255, null=True)),
                ('program_brdcst_area_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_dc', models.CharField(blank=True, max_length=255, null=True)),
                ('program_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_lclas_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_mlsfc_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_sclas_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_nm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_k_drama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbKPop',
            fields=[
                ('k_pop_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brdcst_de', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_end_de', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_time', models.CharField(blank=True, max_length=255, null=True)),
                ('brdcst_tme_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('chnnel_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('female_4_9yo_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n10s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n20s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n30s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n40s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n50s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('female_n60s_above_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('fixing_cast_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('male_4_9yo_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n10s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n20s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n30s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n40s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n50s_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('male_n60s_above_wtchng_rt', models.FloatField(blank=True, null=True)),
                ('program_begin_time', models.CharField(blank=True, max_length=255, null=True)),
                ('program_brdcst_area_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_dc', models.CharField(blank=True, max_length=255, null=True)),
                ('program_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_lclas_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_mlsfc_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_genre_sclas_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('program_nm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_k_pop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbOrganization',
            fields=[
                ('organization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broadcasting_day', models.CharField(max_length=255)),
                ('broadcasting_station', models.CharField(max_length=255)),
                ('broadcasting_time', models.CharField(max_length=255)),
                ('broadcasting_type', models.CharField(max_length=255)),
                ('program_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbOtt',
            fields=[
                ('ott_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_ott',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbOttInfo',
            fields=[
                ('ott_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('save_folder', models.CharField(max_length=255)),
                ('save_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_ott_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbPosterImg',
            fields=[
                ('poster_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('origin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('save_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_poster_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbProfileImg',
            fields=[
                ('profile_img_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_folder', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_profile_img',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbProgram',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('backdrop_path', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_day', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_episode', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_station', models.CharField(blank=True, max_length=255, null=True)),
                ('end_flag', models.TextField()),
                ('poster_img', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_cnt', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbProgramOrganization',
            fields=[
                ('program_organization_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('broadcasting_age', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_day', models.CharField(max_length=255)),
                ('broadcasting_episode', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_rerun', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcasting_station', models.CharField(max_length=255)),
                ('broadcasting_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_program_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRating',
            fields=[
                ('rating_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
            options={
                'db_table': 'tb_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRegion',
            fields=[
                ('region_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbReview',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255)),
                ('date_time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbTvCarrier',
            fields=[
                ('tv_carrier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_tv_carrier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_user',
                'managed': False,
            },
        ),
    ]
