# Generated by Django 3.2.12 on 2022-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('summary', models.CharField(max_length=1000)),
                ('broadcasting_station', models.CharField(max_length=100)),
                ('end_flag', models.BooleanField()),
                ('average_rating', models.FloatField()),
                ('genres', models.ManyToManyField(to='datas.Genre')),
            ],
        ),
    ]
