# Generated by Django 3.2.12 on 2022-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProgram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('summary', models.CharField(max_length=1000)),
                ('broadcasting_station', models.CharField(max_length=100)),
                ('end_flag', models.BooleanField()),
                ('average_rating', models.FloatField()),
                ('genres', models.ManyToManyField(to='datas.Genre')),
            ],
        ),
    ]
