# Generated by Django 3.2.12 on 2022-09-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_allprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
