# Generated by Django 3.2.12 on 2022-09-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_ott'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprogram',
            name='ott',
            field=models.ManyToManyField(to='datas.Ott'),
        ),
        migrations.AddField(
            model_name='program',
            name='ott',
            field=models.ManyToManyField(to='datas.Ott'),
        ),
    ]
