# Generated by Django 3.2.12 on 2022-09-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_auto_20220915_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasAllprogram',
        ),
        migrations.DeleteModel(
            name='DatasAllprogramGenres',
        ),
        migrations.DeleteModel(
            name='DatasGenre',
        ),
        migrations.DeleteModel(
            name='DatasProgram',
        ),
        migrations.DeleteModel(
            name='DatasProgramGenres',
        ),
    ]
